version: "3.8"

services:
  mongodb1:
    image: mongo:latest
    container_name: mongod1b1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: db_name
    volumes:
      - "./data-mongo1:/data/db"
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: db_name
    volumes:
      - type: bind
        source: "./data-mongo2"
        target: "/data/db"
        read_only: false
